# Generated by Django 3.2.7 on 2022-01-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=250)),
                ('prod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProdImages',
            fields=[
                ('img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
