# Generated by Django 3.2.7 on 2022-01-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220108_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_username',
        ),
    ]
