# Generated by Django 3.2.7 on 2022-01-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
